LOADER_CONFIG = {
    "sections_config": [
        {
            "section_name": {"en": "1. About your organisation", "cy": ""},
            "tree_path": "1036.1.1",
            "requires_feedback": None,
        },
        {
            "section_name": {"en": "1.1 Organisation information", "cy": ""},
            "tree_path": "1036.1.1.1",
            "form_name_json": {"en": "organisation-information-cof", "cy": ""},
        },
        {
            "section_name": {"en": "1.2 Applicant information", "cy": ""},
            "tree_path": "1036.1.1.2",
            "form_name_json": {"en": "applicant-information-cof", "cy": ""},
        },
        {"section_name": {"en": "2. About your project", "cy": ""}, "tree_path": "1036.1.2", "requires_feedback": None},
        {
            "section_name": {"en": "2.1 Project information", "cy": ""},
            "tree_path": "1036.1.2.1",
            "form_name_json": {"en": "project-information-cof-25", "cy": ""},
        },
        {
            "section_name": {
                "en": "2.2 Asset information",
                "cy": "2.2 Gwybodaeth am yr ased",
            },
            "form_name_json": {
                "en": "asset-information-cof",
                "cy": "gwybodaeth-am-yr-ased-cof",
            },
            "tree_path": "1036.1.2.2",
        },
        {"section_name": {"en": "3. Strategic case", "cy": ""}, "tree_path": "1036.1.3", "requires_feedback": None},
        {
            "section_name": {"en": "3.1 Community use/significance", "cy": ""},
            "tree_path": "1036.1.3.1",
            "form_name_json": {"en": "community-use-cof", "cy": ""},
        },
        {
            "section_name": {"en": "3.2 Community engagement", "cy": ""},
            "tree_path": "1036.1.3.2",
            "form_name_json": {"en": "community-engagement-cof", "cy": ""},
        },
        {
            "section_name": {"en": "3.3 Local support", "cy": ""},
            "tree_path": "1036.1.3.3",
            "form_name_json": {"en": "local-support", "cy": ""},
        },
        {
            "section_name": {"en": "3.4 Community benefits", "cy": ""},
            "tree_path": "1036.1.3.4",
            "form_name_json": {"en": "community-benefits-cof", "cy": ""},
        },
        {
            "section_name": {"en": "3.5 Environmental sustainability", "cy": ""},
            "tree_path": "1036.1.3.5",
            "form_name_json": {"en": "environmental-sustainability-cof", "cy": ""},
        },
        {"section_name": {"en": "4. Management case", "cy": ""}, "tree_path": "1036.1.4", "requires_feedback": None},
        {
            "section_name": {
                "en": "4.1 Funding required",
                "cy": "4.1 Cyllid sydd ei angen",
            },
            "form_name_json": {
                "en": "funding-required-cof",
                "cy": "cyllid-sydd-ei-angen-cof",
            },
            "tree_path": "1036.1.4.1",
        },
        {
            "section_name": {"en": "4.2 Feasibility ", "cy": ""},
            "tree_path": "1036.1.4.2",
            "form_name_json": {"en": "feasibility-cof", "cy": ""},
        },
        {
            "section_name": {"en": "4.3 Risk", "cy": ""},
            "tree_path": "1036.1.4.3",
            "form_name_json": {"en": "risk-cof", "cy": ""},
        },
        {
            "section_name": {"en": "4.4 Operational costs", "cy": ""},
            "tree_path": "1036.1.4.4",
            "form_name_json": {"en": "operational-costs-cof", "cy": ""},
        },
        {
            "section_name": {"en": "4.5 Skills and resources", "cy": ""},
            "tree_path": "1036.1.4.5",
            "form_name_json": {"en": "skills-and-resources-cof", "cy": ""},
        },
        {
            "section_name": {"en": "4.6 Community representation", "cy": ""},
            "tree_path": "1036.1.4.6",
            "form_name_json": {"en": "community-representation-cof", "cy": ""},
        },
        {
            "section_name": {"en": "4.7 Inclusiveness and integration", "cy": ""},
            "tree_path": "1036.1.4.7",
            "form_name_json": {"en": "inclusiveness-and-integration-cof", "cy": ""},
        },
        {
            "section_name": {"en": "4.8 Upload business plan", "cy": ""},
            "tree_path": "1036.1.4.8",
            "form_name_json": {"en": "upload-business-plan-cof-25", "cy": ""},
        },
        {"section_name": {"en": "5. Declarations", "cy": ""}, "tree_path": "1036.1.5", "requires_feedback": None},
        {
            "section_name": {"en": "5.1 Declarations", "cy": ""},
            "tree_path": "1036.1.5.1",
            "form_name_json": {"en": "declarations-cof", "cy": ""},
        },
    ],
    "fund_config": {
        "id": "604450fe-65c0-4a2e-a4ba-30ccf256056b",
        "short_name": "COF25",
        "welsh_available": True,
        "owner_organisation_name": "None",
        "owner_organisation_shortname": "None",
        "owner_organisation_logo_uri": "None",
        "funding_type": "COMPETITIVE",
        "name_json": {"en": "Community Ownership Fund 2025"},
        "title_json": {"en": "funding to save an asset in your community"},
        "description_json": {
            "en": "The Community Ownership Fund is a £150 million fund over 4 years to support community groups across England, Wales, Scotland and Northern Ireland to take ownership of assets which are at risk of being lost to the community."
        },
    },
    "round_config": {
        "id": "38914fbf-9c31-41be-8547-c24d997aaba2",
        "fund_id": "604450fe-65c0-4a2e-a4ba-30ccf256056b",
        "short_name": "R1",
        "opens": "2024-10-30T11:59:00",
        "assessment_start": "2025-01-01T09:00:00",
        "deadline": "2024-12-11T14:00:00",
        "application_reminder_sent": False,
        "reminder_date": "2024-12-01T11:59:00",
        "assessment_deadline": "2025-01-31T17:00:00",
        "prospectus": "https://www.gov.uk/government/publications/community-ownership-fund-prospectus/community-ownership-fund-2025-prospectus",
        "privacy_notice": "https://www.gov.uk/government/organisations/ministry-of-housing-communities-local-government",
        "reference_contact_page_over_email": False,
        "contact_email": "COF@communities.gov.uk",
        "contact_phone": "0",
        "contact_textphone": "0",
        "support_times": "9am to 5pm",
        "support_days": "Monday to Friday",
        "instructions_json": {
            "en": "You must have received an invitation to apply. If we did not invite you, first <a href='https://www.gov.uk/guidance/community-ownership-fund-round-4-how-to-express-your-interest-in-applying'>express your interest in the fund</a>.",
            "cy": "",
        },
        "feedback_link": "https://www.gov.uk/government/organisations/ministry-of-housing-communities-local-government",
        "project_name_field_id": "apGjFS",
        "application_guidance_json": {
            "en": "<h2 class='govuk-heading govuk-heading-s'>What we'll ask you for</h2><p class='govuk-body'>You can preview the <a href='{all_questions_url}'>full list of application questions</a>.</p><p class='govuk-body'>We'll also ask you to upload a business plan to support the answers you've given us in the management case section.</p>",
            "cy": "",
        },
        "guidance_url": "https://www.gov.uk/government/organisations/ministry-of-housing-communities-local-government",
        "all_uploaded_documents_section_available": False,
        "application_fields_download_available": True,
        "display_logo_on_pdf_exports": False,
        "mark_as_complete_enabled": True,
        "is_expression_of_interest": False,
        "eoi_decision_schema": None,
        "feedback_survey_config": {
            "has_feedback_survey": True,
            "has_section_feedback": True,
            "is_feedback_survey_optional": False,
            "is_section_feedback_optional": False,
        },
        "eligibility_config": {"has_eligibility": False},
        "title_json": {"en": "Round 1"},
        "contact_us_banner_json": {
            "en": '<h2 class="govuk-heading-m">Get application support</h2>\r\n                 <p class="govuk-body">\r\n                    <a class="govuk-link" href="https://mycommunity.org.uk/community-ownership-fund">Visit the My Community website</a>\r\n                    for information and guidance on applying to Community Ownership Fund.\r\n                    <a class="govuk-link" href="https://mycommunity.org.uk/community-ownership-fund#enquiry-form">Fill out the enquiry form</a>\r\n                    to request advice from My Community.\r\n                </p>\r\n                <p class="govuk-body">\r\n                    We cannot provide direct support to applicants outside of this service.\r\n                </p>\r\n                <h2 class="govuk-heading-m">Get technical support</h2>\r\n                <p  class="govuk-body">\r\n                    Contact the Department of Levelling Up, Housing and Communities funding team if you need\r\n                    help with accessing or submitting an application form.\r\n                </p>',
            "cy": "",
        },
    },
    "base_path": 1036,
}
