LOADER_CONFIG = {
    "sections_config": [
        {
            "section_name": {"en": "1. General Information", "cy": ""},
            "tree_path": "1001.1.1",
            "requires_feedback": None,
        },
        {
            "section_name": {"en": "1.1 Project Name Sample", "cy": ""},
            "tree_path": "1001.1.1.1",
            "form_name_json": {"en": "project-name-sample", "cy": ""},
        },
        {
            "section_name": {"en": "1.2 Organisation Name Sample", "cy": ""},
            "tree_path": "1001.1.1.2",
            "form_name_json": {"en": "organisation-name-sample", "cy": ""},
        },
    ],
    "fund_config": {
        "id": "91504db1-2f21-4177-ac1b-05c9246d5b55",
        "short_name": "SF",
        "welsh_available": False,
        "owner_organisation_name": "None",
        "owner_organisation_shortname": "None",
        "owner_organisation_logo_uri": "None",
        "funding_type": "UNCOMPETED",
        "name_json": {"en": "Sample Fund"},
        "title_json": {"en": "Sample Fund"},
        "description_json": {"en": "This is a sample fund."},
    },
    "round_config": {
        "id": "f54d5cfa-79b5-4706-9c55-37cc927af66f",
        "fund_id": "91504db1-2f21-4177-ac1b-05c9246d5b55",
        "short_name": "R1",
        "opens": "2024-11-01T00:00:00",
        "assessment_start": "2024-11-01T00:00:00",
        "deadline": "2025-05-01T00:00:00",
        "application_reminder_sent": False,
        "reminder_date": "2024-11-01T00:00:00",
        "assessment_deadline": "2025-05-01T00:00:00",
        "prospectus": "https://link.co.uk",
        "privacy_notice": "https://link.co.uk",
        "reference_contact_page_over_email": False,
        "contact_email": "dev@communities.gov.uk",
        "contact_phone": "",
        "contact_textphone": "",
        "support_times": "10",
        "support_days": "7",
        "instructions_json": {"en": None, "cy": None},
        "feedback_link": "https://link.co.uk",
        "project_name_field_id": "VcyKVN",
        "application_guidance_json": {"en": None, "cy": None},
        "guidance_url": "https://link.co.uk",
        "all_uploaded_documents_section_available": False,
        "application_fields_download_available": False,
        "display_logo_on_pdf_exports": False,
        "mark_as_complete_enabled": False,
        "is_expression_of_interest": False,
        "eoi_decision_schema": {"en": {}, "cy": {}},
        "feedback_survey_config": {
            "has_feedback_survey": "false",
            "has_section_feedback": "false",
            "has_research_survey": "false",
            "is_feedback_survey_optional": "false",
            "is_section_feedback_optional": "false",
            "is_research_survey_optional": "false",
        },
        "eligibility_config": {"has_eligibility": False},
        "title_json": {"en": "Round 1", "cy": None},
        "contact_us_banner_json": {"en": None, "cy": None},
    },
    "base_path": 1001,
}
