services:
  fsd-fund-store:
    build:
      context: ./src
      target: fund-store-dev
    volumes:
      - .:/workspace:cached
    command: sleep infinity
    environment:
      - DATABASE_URL=postgresql://postgres:password@fund-store-db:5432/fund_store
    # depends_on:
    #   - fund-store-db
  fund-store-db:
    image: postgres
    # ports:
    #   - 5433:5432
    environment:
      - POSTGRES_PASSWORD=password
