services:
  fund-store:
    build:
      context: .
      target: fund-store-dev
    volumes:
      - .:/fund-store:cached
    command: sleep infinity
    environment:
      - DATABASE_URL=postgresql://postgres:password@fund-store-db:5432/fund_store


  fund-store-db:
    image: postgres
    environment:
     - POSTGRES_PASSWORD=password
