[package]
name = "funding-service-design-fund-store"
version = "0.1.1"
description = "The funding service design fund store for the DLUHC."
authors = ["Version One", "HM Government, Department of Levelling Up, Housing and Communities"]
license = "MIT License"

[tool.black]
line-length = 120
exclude = ['config/fund_loader_config/FAB/*']

[tool.flake8]
max-line-length = 120
ignore = ['E203', 'W503']
count = true
exclude = ['config/fund_loader_config/FAB/*']

[tool.isort]
profile = "black"
force_single_line = "true"
