"""empty message

Revision ID: f095a3913993
Revises: 52c81aefc1fe
Create Date: 2023-05-24 12:29:34.376422

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f095a3913993"
down_revision = "52c81aefc1fe"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("fund", schema=None) as batch_op:
        batch_op.add_column(sa.Column("welsh_available", sa.Boolean(), default=False))
    op.execute(sa.text("Update fund set welsh_available=True;"))
    op.alter_column("fund", "welsh_available", nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("fund", schema=None) as batch_op:
        batch_op.drop_column("welsh_available")

    # ### end Alembic commands ###
