"""Add 'eligibility_config' column to round table, with default value

Revision ID: e8552f721767
Revises: 0feae1606cfa
Create Date: 2023-11-13 14:52:37.892469

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e8552f721767"
down_revision = "0feae1606cfa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("round", schema=None) as batch_op:
        batch_op.add_column(sa.Column("eligibility_config", sa.JSON(none_as_null=True), nullable=True))
    connection = op.get_bind()
    connection.execute(
        sa.text(
            """
            UPDATE round
            SET eligibility_config = '{"has_eligibility": false}'
            """
        )
    )
    with op.batch_alter_table("round", schema=None) as batch_op:
        batch_op.alter_column(sa.Column("eligibility_config", nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("round", schema=None) as batch_op:
        batch_op.drop_column("eligibility_config")

    # ### end Alembic commands ###
