openapi: "3.0.0"

info:
  title: Funding Service Design - Fund store.
  description: Fund store API for DLUHC Funding Service Design
  version: "0.1.0"

paths:
  /db/funds:
    get:
      tags:
        - DB_Funds
      summary: Returns list of all funds
      description: Returns list of all funds
      operationId: api.routes.get_funds
      responses:
        200:
          description: "List all funds."
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref : 'components.yml#/components/schemas/Fund'
        404:
          description: "No funds exist"
          content:
              texts/plain:
                schema:
                  $ref: 'components.yml#/components/schemas/Error'
  /db/funds/{fund_id}:
    get:
      operationId: api.routes.get_fund
      tags:
        - DB_Funds
      parameters:
        - $ref: "components.yml#/components/parameters/fund_id"
        - name: language
          in: query
          schema:
            type: string
        - name: use_short_name
          in: query
          schema:
            type: boolean
          required: false
      responses:
        200:
          description: "If the fund exists then the data is returned."
          content:
            application/json:
              schema:
                $ref: 'components.yml#/components/schemas/Fund'
        404:
          description: "Fund not found"
          content:
              texts/plain:
                schema:
                  $ref: 'components.yml#/components/schemas/Error'

  /db/funds/{fund_id}/rounds/{round_id}:
    get:
      tags:
        - DB_Rounds
      summary: Returns the data on a specified round for a specific fund.
      description: Given a fund ID and a round ID we return the relavant round data.
      operationId: api.routes.get_round
      parameters:
        - $ref: "components.yml#/components/parameters/fund_id"
        - name: round_id
          in: path
          schema:
            type: string
          required: true
        - name: language
          in: query
          schema:
            type: string
        - name: use_short_name
          in: query
          schema:
            type: boolean
          required: false
      responses:
        200:
          description: "If the round exists then the data is returned."
          # content:
          #   application/json:
              # schema:
              #   $ref: 'components.yml#/components/schemas/Round'
        404:
          description: "Round not found from given fund id and round id."
          content:
              application/json:
                schema:
                  $ref: 'components.yml#/components/schemas/Error'

  /db/funds/{fund_id}/rounds:
    get:
      tags:
        - DB_Rounds
      summary: Given a fund ID we return all rounds for that fund.
      description: Given a fund ID we return all rounds for that fund.
      operationId: api.routes.get_rounds_for_fund
      parameters:
        - in: path
          name: fund_id
          schema:
            type: string
          required: true
        - name: use_short_name
          in: query
          schema:
            type: boolean
          required: false
      responses:
        200:
          description: A list of rounds matching the given fund ID.
          # content:
          #   application/json:
          #     schema:
          #       type: array
                # items:
                #   $ref : 'components.yml#/components/schemas/Round'
        404:
          description: "Rounds page not found for given fund id."
          content:
            application/json:
              schema:
                $ref: "components.yml#/components/schemas/Error"
  /db/funds/{fund_id}/rounds/{round_id}/sections/application:
    get:
      tags:
        - DB_Sections
      summary: Returns the application sections for the given round
      description: Given a fund ID and a round ID we return the display sections for Application
      operationId: api.routes.get_sections_for_round_application
      parameters:
        - $ref: "components.yml#/components/parameters/fund_id"
        - name: round_id
          in: path
          schema:
            type: string
          required: true
        - name: language
          in: query
          schema:
            type: string
      responses:
        200:
          description: "If the round exists then the sections are returned."
        404:
          description: "If an invalid fund/round ID is supplied"
  /db/funds/{fund_id}/rounds/{round_id}/sections/assessment:
    get:
      tags:
        - DB_Sections
      summary: Returns the assessment sections for the given round
      description: Given a fund ID and a round ID we return the display sections for assessment
      operationId: api.routes.get_sections_for_round_assessment
      parameters:
        - $ref: "components.yml#/components/parameters/fund_id"
        - name: round_id
          in: path
          schema:
            type: string
          required: true
        - name: language
          in: query
          schema:
            type: string
      responses:
        200:
          description: "If the round exists then the sections are returned."
        404:
          description: "If an invalid fund/round ID is supplied"

  /funds:
    get:
      tags:
        - Funds
      summary: Returns list of all funds
      description: Returns list of all funds
      operationId: core.funds.get_funds
      responses:
        200:
          description: "List all funds."
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref : 'components.yml#/components/schemas/Fund'
        404:
          description: "No funds exist"
          content:
              texts/plain:
                schema:
                  $ref: 'components.yml#/components/schemas/Error'

  /funds/{fund_id}/rounds/{round_id}:
    get:
      tags:
        - Rounds
      summary: Returns the data on a specified round for a specific fund.
      description: Given a fund ID and a round ID we return the relavant round data.
      operationId: core.rounds.get_round
      parameters:
        - $ref: "components.yml#/components/parameters/fund_id"
        - name: round_id
          in: path
          schema:
            type: string
          required: true
        - name: language
          in: query
          schema:
            type: string
        - name: use_short_name
          in: query
          schema:
            type: boolean
          required: false
      responses:
        200:
          description: "If the round exists then the data is returned."
          content:
            application/json:
              schema:
                $ref: 'components.yml#/components/schemas/Round'
        404:
          description: "Round not found from given fund id and round id."
          content:
              application/json:
                schema:
                  $ref: 'components.yml#/components/schemas/Error'

  /funds/{fund_id}:
    get:
      tags:
        - Funds
      summary: Returns the data on a specified fund.
      description: Given a fund ID we return the relevant fund data.
      operationId: core.funds.get_fund
      parameters:
        - $ref: "components.yml#/components/parameters/fund_id"
        - name: language
          in: query
          schema:
            type: string
        - name: use_short_name
          in: query
          schema:
            type: boolean
          required: false
      responses:
        200:
          description: "If the fund exists then the data is returned."
          content:
            application/json:
              schema:
                $ref: 'components.yml#/components/schemas/Fund'
        404:
          description: "Fund page not found for given fund id."
          content:
              texts/plain:
                schema:
                  $ref: 'components.yml#/components/schemas/Error'

  /funds/{fund_id}/rounds:
    get:
      tags:
        - Rounds
      summary: Given a fund ID we return all rounds for that fund.
      description: Given a fund ID we return all rounds for that fund.
      operationId: core.rounds.get_rounds_for_fund
      parameters:
        - in: path
          name: fund_id
          schema:
            type: string
          required: true
        - name: use_short_name
          in: query
          schema:
            type: boolean
          required: false
      responses:
        200:
          description: A list of rounds matching the given fund ID.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref : 'components.yml#/components/schemas/Round'
        404:
          description: "Rounds page not found for given fund id."
          content:
            application/json:
              schema:
                $ref: "components.yml#/components/schemas/Error"

tags:
  - name: Funds
    description: "See all funds or find a fund"
  - name: Rounds
    description: "See all rounds or find a round"
