"""empty message

Revision ID: 105be0c28863
Revises: 52c81aefc1fe
Create Date: 2023-05-24 11:03:20.786770

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision = "105be0c28863"
down_revision = "52c81aefc1fe"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("round", schema=None) as batch_op:
        batch_op.add_column(sa.Column("welsh_available", sa.Boolean(), default=False))
    op.execute(text("Update round set welsh_available=False;"))
    op.alter_column("round", "welsh_available", nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("round", schema=None) as batch_op:
        batch_op.drop_column("welsh_available")

    # ### end Alembic commands ###
