"""empty message

Revision ID: 2188a6d1b0a3
Revises: 979f716a566d
Create Date: 2023-05-02 13:14:42.205050

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = "2188a6d1b0a3"
down_revision = "979f716a566d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("assessment_field", schema=None) as batch_op:
        batch_op.create_unique_constraint(
            batch_op.f("uq_assessment_field_id"), ["id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("assessment_field", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("uq_assessment_field_id"), type_="unique"
        )

    # ### end Alembic commands ###
