"""empty message

Revision ID: 4463ff0b0e9c
Revises: 024379c68dfe
Create Date: 2023-07-25 15:50:44.107992

"""

import sqlalchemy
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4463ff0b0e9c"
down_revision = "024379c68dfe"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("fund", schema=None) as batch_op:
        batch_op.drop_column("all_uploaded_documents_section_available")

    with op.batch_alter_table("round", schema=None) as batch_op:
        batch_op.add_column(sa.Column("all_uploaded_documents_section_available", sa.Boolean(), nullable=True))

    connection = op.get_bind()
    connection.execute(
        sqlalchemy.text(
            """
            UPDATE round
            SET all_uploaded_documents_section_available = false
            """
        )
    )

    connection.execute(
        sqlalchemy.text(
            """
            UPDATE round
            SET all_uploaded_documents_section_available = true
            WHERE fund_id = '47aef2f5-3fcb-4d45-acb5-f0152b5f03c4'
            """
        )
    )

    with op.batch_alter_table("round", schema=None) as batch_op:
        batch_op.alter_column("all_uploaded_documents_section_available", nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("round", schema=None) as batch_op:
        batch_op.drop_column("all_uploaded_documents_section_available")

    with op.batch_alter_table("fund", schema=None) as batch_op:
        batch_op.add_column(sa.Column("all_uploaded_documents_section_available", sa.Boolean(), nullable=True))

    connection = op.get_bind()
    connection.execute(
        sqlalchemy.text(
            """
            UPDATE fund
            SET all_uploaded_documents_section_available = false
            """
        )
    )

    connection.execute(
        sqlalchemy.text(
            """
            UPDATE fund
            SET all_uploaded_documents_section_available = true
            WHERE short_name = 'COF'
            """
        )
    )

    with op.batch_alter_table("fund", schema=None) as batch_op:
        batch_op.alter_column("all_uploaded_documents_section_available", nullable=False)
    # ### end Alembic commands ###
