"""empty message

Revision ID: 52c81aefc1fe
Revises: 6ebd1fa1288c
Create Date: 2023-05-09 14:09:42.521125

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "52c81aefc1fe"
down_revision = "6ebd1fa1288c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "form_name",
        sa.Column("section_id", sa.Integer(), nullable=False),
        sa.Column("form_name", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["section_id"],
            ["section.id"],
            name=op.f("fk_form_name_section_id_section"),
        ),
        sa.PrimaryKeyConstraint("section_id", "form_name", name=op.f("pk_form_name")),
    )
    with op.batch_alter_table("assessment_field", schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f("uq_assessment_field_id"), ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("assessment_field", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("uq_assessment_field_id"), type_="unique")

    op.drop_table("form_name")
    # ### end Alembic commands ###
