"""empty message

Revision ID: 5953c7f64f0f
Revises: 3fec32b0a1e3
Create Date: 2023-05-02 16:36:06.515366

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = "5953c7f64f0f"
down_revision = "3fec32b0a1e3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("assessment_field", schema=None) as batch_op:
        batch_op.create_unique_constraint(
            batch_op.f("uq_assessment_field_id"), ["id"]
        )

    with op.batch_alter_table("section", schema=None) as batch_op:
        batch_op.create_index(
            "ix_sections_path", ["path"], unique=False, postgresql_using="gist"
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("section", schema=None) as batch_op:
        batch_op.drop_index("ix_sections_path", postgresql_using="gist")

    with op.batch_alter_table("assessment_field", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("uq_assessment_field_id"), type_="unique"
        )

    # ### end Alembic commands ###
