"""empty message

Revision ID: e6223cb02ea7
Revises: 91934df64d2d
Create Date: 2023-09-08 11:18:12.864272

"""
import sqlalchemy
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'e6223cb02ea7'
down_revision = '91934df64d2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('round', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mark_as_complete_available', sa.Boolean(), nullable=False))

    connection = op.get_bind()
    connection.execute(
        sqlalchemy.text(
            """
            UPDATE round
            SET mark_as_complete_available = false
            """
        )
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('round', schema=None) as batch_op:
        batch_op.drop_column('mark_as_complete_available')

    # ### end Alembic commands ###
