"""empty message

Revision ID: f5d2a21f372e
Revises: 44191ee43f88
Create Date: 2024-10-14 09:26:18.550391

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f5d2a21f372e"
down_revision = "44191ee43f88"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("event", schema=None) as batch_op:
        batch_op.alter_column("round_id", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###

    op.execute("ALTER TYPE public.event_type ADD VALUE IF NOT EXISTS 'ACCOUNT_IMPORT'")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("event", schema=None) as batch_op:
        batch_op.alter_column("round_id", existing_type=sa.UUID(), nullable=False)

    # ### end Alembic commands ###
