"""empty message

Revision ID: 7b877df0bd36
Revises: 2fd177385a5c
Create Date: 2024-03-21 14:11:56.510506

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7b877df0bd36"
down_revision = "2fd177385a5c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("round", schema=None) as batch_op:
        batch_op.alter_column("application_reminder_sent", existing_type=sa.BOOLEAN(), nullable=False)
        batch_op.alter_column("is_expression_of_interest", existing_type=sa.BOOLEAN(), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("round", schema=None) as batch_op:
        batch_op.alter_column("is_expression_of_interest", existing_type=sa.BOOLEAN(), nullable=True)
        batch_op.alter_column("application_reminder_sent", existing_type=sa.BOOLEAN(), nullable=True)

    # ### end Alembic commands ###
