"""Add ggis_scheme_reference_number

Revision ID: 71ec50f94e6f
Revises: de8d7954ffda
Create Date: 2024-11-13 13:49:03.498795

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "71ec50f94e6f"
down_revision = "de8d7954ffda"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("fund", schema=None) as batch_op:
        batch_op.add_column(sa.Column("ggis_scheme_reference_number", sa.String(length=255), nullable=True))

    with op.batch_alter_table("round", schema=None) as batch_op:
        batch_op.alter_column("reference_contact_page_over_email", existing_type=sa.BOOLEAN(), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("round", schema=None) as batch_op:
        batch_op.alter_column("reference_contact_page_over_email", existing_type=sa.BOOLEAN(), nullable=True)

    with op.batch_alter_table("fund", schema=None) as batch_op:
        batch_op.drop_column("ggis_scheme_reference_number")

    # ### end Alembic commands ###
