"""empty message

Revision ID: ed3a28891090
Revises: 4c33c5e0a6c8
Create Date: 2024-02-07 13:45:40.870986

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ed3a28891090"
down_revision = "4c33c5e0a6c8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("round", schema=None) as batch_op:
        batch_op.add_column(sa.Column("eoi_decision_schema ", sa.JSON(none_as_null=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("round", schema=None) as batch_op:
        batch_op.drop_column("eoi_decision_schema ")

    # ### end Alembic commands ###
