"""FS-2563: Add Event table

Revision ID: 7ff731a56afb
Revises: 8e4d1e36ebbf
Create Date: 2024-05-21 09:32:17.418663

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7ff731a56afb"
down_revision = "8e4d1e36ebbf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("round_id", sa.UUID(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("activation_date", sa.DateTime(), nullable=False),
        sa.Column("processed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["round_id"], ["round.id"], name=op.f("fk_event_round_id_round")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("event")
    # ### end Alembic commands ###
