"""empty message

Revision ID: 2fd177385a5c
Revises: 101ca9d39e50
Create Date: 2024-03-21 13:56:05.591754

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2fd177385a5c"
down_revision = "101ca9d39e50"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("round", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_expression_of_interest", sa.Boolean(), nullable=True))

    connection = op.get_bind()
    connection.execute(
        sa.text(
            """
            UPDATE round
            SET is_expression_of_interest = false
            WHERE id not in ('6a47c649-7bac-4583-baed-9c4e7a35c8b3')
            """
        )
    )
    connection.execute(
        sa.text(
            """
            UPDATE round
            SET is_expression_of_interest = true
            WHERE id in ('6a47c649-7bac-4583-baed-9c4e7a35c8b3')
            """
        )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("round", schema=None) as batch_op:
        batch_op.drop_column("is_expression_of_interest")
    # ### end Alembic commands ###
