an_sorted_application_sections_SAMPLE = [
    {'section_name': '1. About your organisation', 'tree_path': '1'},
    {'section_name': '1.1 Organisation Information', 'form_name':'organisation-information-cof-r3-w1','tree_path': '1.1'},
    {'section_name': '1.2 Applicant Information', 'form_name':'applicant-information-cof-r3-w1', 'tree_path': '1.2'},
    {'section_name': '2. About your project', 'tree_path': '2'},
    {'section_name': '2.1 Project Information', 'form_name':'project-information-cof-r3-w1', 'tree_path': '2.1'},
    {'section_name': '2.2 Asset Information', 'form_name':'asset-information-cof-r3-w1', 'tree_path': '2.2'},
    {'section_name': '3. Strategic case', 'tree_path': '3'},
    {'section_name': '3.1 Community Use', 'form_name':'community-use-cof-r3-w1', 'tree_path': '3.1'},
    {'section_name': '3.2 Community Engagement', 'form_name':'community-engagement-cof-r3-w1', 'tree_path': '3.2'},
    {'section_name': '3.3 Local Support', 'form_name':'local-support-cof-r3-w1', 'tree_path': '3.3'},
    {'section_name': '3.4 Community benefits', 'form_name':'community-benefits-cof-r3-w1', 'tree_path': '3.4'},
    {'section_name': '3.5 Environmental Sustainability', 'form_name':'environmental-sustainability-cof-r3-w1', 'tree_path': '3.5'},
    {'section_name': '4. Management case', 'tree_path': '4'},
    {'section_name': '4.1 Funding Required', 'form_name':'funding-required-cof-r3-w1', 'tree_path': '4.1'},
    {'section_name': '4.2 Feasibility', 'form_name':'feasibility-cof-r3-w1', 'tree_path': '4.2'},
    {'section_name': '4.3 Risk', 'form_name':'feasibility-cof-r3-w1', 'tree_path': '4.3'},
    {'section_name': '4.4 Operational costs', 'form_name':'operational-costs-cof-r3-w1', 'tree_path': '4.4'},
    {'section_name': '4.5 Skills and resources', 'form_name':'skills-and-resources-cof-r3-w1', 'tree_path': '4.5'},
    {'section_name': '4.6 Community representation', 'form_name':'community-representation-cof-r3-w1', 'tree_path': '4.6'},
    {'section_name': '4.7 Inclusiveness and integration', 'form_name':'inclusiveness-and-integration-cof-r3-w1', 'tree_path': '4.7'},
    {'section_name': '4.8 Upload business plan', 'form_name':'upload-business-plan-cof-r3-w1', 'tree_path': '4.8'},
    {'section_name': '5. Subsidy control and state aid', 'tree_path': '5'},
    {'section_name': '5.1 Project qualification', 'form_name':'project-qualifications-cof-r3-w1', 'tree_path': '5.1'},
    {'section_name': '6. Check declarations', 'tree_path': '6'},
    {'section_name': '6.1 Project qualification', 'form_name':'project-information-cof-r3-w1', 'tree_path': '6.1'}
]
ROUND_3 = "e85ad42f-73f5-4e1b-a1eb-6bc5d7f3d762"
