import sys

import click

sys.path.insert(1, ".")

from db.models.section import Section  # noqa: E402
from db.queries import (  # noqa: E402
    get_application_sections_for_round,
    get_round_by_short_name,
)  # noqa: E402
from app import create_app  # noqa: E402
from airium import Airium  # noqa: E402
from scripts.all_questions.read_forms import (  # noqa: E402
    find_forms_dir,
)  # , build_form  # noqa: E402
from scripts.all_questions.metadata_utils import (  # noqa: E402
    generate_print_data_for_sections,
)  # noqa: E402

# Initialise Airium html printer
air = Airium()

# Define start and end html
BOILERPLATE_START = """
{% extends "base.html" %}
{%- from 'govuk_frontend_jinja/components/inset-text/macro.html' import govukInsetText -%}
{%- from "govuk_frontend_jinja/components/button/macro.html" import govukButton -%}

{% from "partials/file-formats.html" import file_formats %}
{% set pageHeading %}{% trans %}Full list of application questions{% endtrans %}{% endset %}
{% block content %}
<div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
        <span class="govuk-caption-l">{% trans %}{{fund_title}}{% endtrans %} {{round_title}}</span>
        <h1 class="govuk-heading-xl">{{pageHeading}}</h1>
"""

BOILERPLATE_END = """
    </div>
</div>
{% endblock %}
"""


def print_html_toc(air: Airium, sections: dict):
    """Prints a table of contents for the supplied sections to the supplied `Airium` instance

    Args:
        air (Airium): Instance to write html to
        sections (dict): Sections for this TOC
    """
    # TODO test translations
    with air.h2(klass="govuk-heading-m "):
        air("{% trans %}Table of contents{% endtrans %}")
    with air.ol(klass="govuk-list govuk-list--number"):
        for anchor, details in sections.items():
            with air.li():
                with air.a(klass="govuk-link", href=f"#{anchor}"):
                    air(details["title_text"])


def print_components(air: Airium, components: list):
    """Prints the components within a page

    Args:
        air (Airium): Instance to print html
        components (list): List of components to print
    """
    for c in components:
        # Print the title
        if not c["hide_title"] and c["title"] is not None:
            with air.p(klass="govuk-body"):
                air(f"{c['title']}")

        for t in c["text"]:
            # Print lists as <ul> bullet lists
            if isinstance(t, list):
                with air.ul(klass="govuk-list govuk-list--bullet"):
                    for bullet in t:
                        with air.li(klass=""):
                            air(bullet)
            else:
                # Just print the text
                with air.p(klass="govuk-body"):
                    air(t)


def print_html(sections: dict) -> str:
    """Prints the html for the supplied sections

    Args:
        sections (dict): All sections to print, as generated by `metadata_utils.generate_print_data_for_sections`

    Returns:
        str: HTML string
    """
    with air.div(klass="govuk-!-margin-bottom-8"):
        # Print Table of Contents
        print_html_toc(air, sections)
        idx_section = 1

        for anchor, details in sections.items():
            air.hr(
                klass=(
                    "govuk-section-break govuk-section-break--l"
                    " govuk-section-break--visible"
                )
            )

            # Print each section header, with anchor
            with air.h2(klass="govuk-heading-l", id=anchor):
                air(f"{idx_section}. {details['title_text']}")

            form_print_data = details["form_print_data"]
            # Sort in order of numbered headings
            for heading in sorted(
                form_print_data,
                key=lambda item: str((form_print_data[item])["heading_number"]),
            ):
                header_info = form_print_data[heading]
                # Print header for this form
                if header_info["is_form_heading"]:
                    with air.h3(klass="govuk-heading-m"):
                        air(f"{header_info['heading_number']}. {header_info['title']}")

                else:
                    # Print header for this form page
                    with air.h4(klass="govuk-heading-s"):
                        air(f"{header_info['heading_number']}. {header_info['title']}")

                # Print components within this form
                print_components(air, header_info["components"], 0)

            idx_section += 1

    # Concatenate start html, generated html and end html to one string and return
    html = f"{BOILERPLATE_START}{str(air)}{BOILERPLATE_END}"
    print(html)
    return html


@click.command()
@click.option("--fund_short_code", default="DPIF", help="Fund short code", prompt=True)
@click.option("--round_short_code", default="R2", help="Round short code", prompt=True)
@click.option(
    "--lang",
    default="en",
    help="Language - used when a round supports english and welsh",
    prompt=True,
    type=click.Choice(["en", "cy"]),
)
@click.option(
    "--output_location",
    default="/Users/sarahsloan/dev/CommunitiesUkWorkspace/funding-service-design-frontend/app/templates/",
    help="Folder to write output html to",
    prompt=True,
)
@click.option(
    "--forms_dir",
    default="/Users/sarahsloan/dev/CommunitiesUkWorkspace/digital-form-builder/fsd_config/form_jsons/",
    help="Local, absolute path, to the form JSONs to use to generate question lists",
    prompt=True,
)
def generate_all_questions(
    fund_short_code=None,
    round_short_code=None,
    lang=None,
    output_location=None,
    forms_dir=None,
):
    app = create_app()
    with app.app_context():
        round = get_round_by_short_name(fund_short_code, round_short_code)
        sections: list[Section] = get_application_sections_for_round(
            round.fund_id, round.id
        )

        path_to_form_jsons = find_forms_dir(
            forms_dir, fund_short_code, round_short_code, lang
        )

        section_map = generate_print_data_for_sections(
            sections=sections, path_to_form_jsons=path_to_form_jsons, lang=lang
        )

        html_str = print_html(
            sections=section_map,
            lang=lang,
        )
        filename = f"{fund_short_code.casefold()}_{round_short_code.casefold()}_all_questions.html"
        with open(f"{output_location}{filename}", "w") as f:
            f.write(html_str)


if __name__ == "__main__":
    generate_all_questions()
