name: Deploy fds-fund-store to Gov PaaS

permissions:
  packages: write

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**/README.md'

env:
  REGISTRY: ghcr.io
  DOCKER_IMAGE: funding-service-design-fund-store

jobs:
  test_and_deploy:
    uses: communitiesuk/funding-design-service-workflows/.github/workflows/deploy.yml@FS-2406
    with:
      app_name: ${{ github.event.repository.name }}
      api: true
      run_performance_tests: true
      run_e2e_tests: true
    secrets:
      CF_API: ${{secrets.CF_API}}
      CF_ORG: ${{secrets.CF_ORG}}
      CF_SPACE: ${{secrets.CF_SPACE}}
      CF_USER: ${{secrets.CF_USERNAME}}
      CF_PASSWORD: ${{secrets.CF_PASSWORD}}
      E2E_PAT: ${{secrets.E2E_PAT}}
  paketo_build:
    needs: test_and_deploy
    runs-on: ubuntu-latest
    name: Packaging and building the application
    steps:
      - uses: buildpacks/github-actions/setup-pack@v5.0.0
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and publish app image
        run: "pack build ${{ env.DOCKER_IMAGE }} --builder paketobuildpacks/builder:base"

      - name: Push image
        run: |
          IMAGE_ID=${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.DOCKER_IMAGE }}

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Use Docker `latest` tag convention
          [ "$VERSION" == "main" ] && VERSION=latest

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker tag ${{ env.DOCKER_IMAGE }} $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
